project:
  type: website
  
  resources:
    - "1. session_sheets/*.R"
    - "2. homework_questions/*.R"
    - "3. homework_answers/*"
    - "data/**"

website:
  title: "MRCG intro to R"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: timetable.qmd
        text: Timetable
      - href: resources.qmd
        text: Resources
      - href: stats_explained.qmd
        text: Statistics Refresher

format:
  lshtm-mrcg-html:
    css: styles.css
    toc: true

editor: visual

