---
format: lshtm-mrcg-html
toc: false
page-layout: full
---

# Weekly Timetable

| Session | Date | Venue | Scripts | Data | Recordings | Homework | Answers |
|----|----|----|----|----|----|----|----|
| Introduction | 3rd August | F001 | [download](session_sheets/week_one_session.R){download="week_one_session.R"} | \- | [video](https://lshtm.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=e21b206d-2ade-4c48-8937-b49b01161f26) | [download](homework_questions/week_one_homework.R){download="week_one_homework.R"} | [answers](homework_answers/week_one_answers.qmd) |
| More complex data types | 10th August | Rees | [download](session_sheets/week_two_session.R){download="week_two_session.R"} | \- | [video](https://lshtm.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=33209480-1831-4b3e-951a-b4a300981a71) | [download](homework_questions/week_two_homework.R){download="week_two_homework.R"} | [answers](homework_answers/week_two_answers.qmd) |
| Data importing and packages | 17th August | Rees | [download](session_sheets/week_three_session.R) | [csv](data/iris.csv){download="iris.csv"} / [xlsx](data/iris.xlsx){download="iris.xlsx"} | [video](https://lshtm.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=548c67f3-af3d-4d3d-9151-b4a90146118a) | [download](homework_questions/week_three_homework.R) | [answers](homework_answers/week_three_answers.qmd) |
| More tidyverse & basic statistical analysis | 24th August | Rees | \- | \- | \- | \- | \- |
| Visulisation with ggplot | 31st August | Rees | \- | [csv](data/air.csv){download="air.csv"} | \- | \- | \- |
| Break (7th & 14th September) | ======== | ====== | ======= | ====== | ======= | ======== | ======= |
